//> using scala "3.3.6"
//> using dep "com.github.pathikrit::better-files:3.9.2"
//> using dep "org.scalameta::munit:1.1.1"
//> using dep "org.scalactic::scalactic:3.2.19"

//> using option "-deprecation"
//> using option "-encoding" "utf-8"
//> using option "-explain-types"
//> using option "-explain"
//> using option "-feature"
//> using option "-unchecked"
//> using option "-Ysafe-init"
//> using option "-Ycheck-all-patmat"
//> using option "-Ycheck-reentrant"
//> using option "-Wvalue-discard"
//> using option "-Wnonunit-statement"
//> using option "-Wunused:imports,privates,locals,explicits,implicits,params,linted"

//> using mainClass "fr.esgi.al.funprog.Main"
